_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
C:
    value: 200
Model:
    value: |-
        DQN(
          (linear1): Linear(in_features=16, out_features=128, bias=True)
          (linear2): Linear(in_features=128, out_features=64, bias=True)
          (output): Linear(in_features=64, out_features=1, bias=True)
        )
batch_size:
    value: 64
checkpoint:
    value: Data/checkpoint2
decay:
    value: 5000
device:
    value: cpu
epochs:
    value: 200000
gamma:
    value: 0.99
learning_rate:
    value: 0.001
name:
    value: Mancala 2
start_epoch:
    value: 0
